### ISSUE TITLE
Add 'An official California State Government website' banner

### ISSUE THREAD

**Issue by lukefretwell** [Office-of-Digital-Innovation/California-State-Web-Template#29]
Suggest adding “An official California State Government website” banner to the template, similar to what US Web Design System does for the federal government:

* Reference: https://designsystem.digital.gov/components/headers/#basic
* Demo: https://designsystem.digital.gov/components/headers/basic/

Code:

`      <div class="usa-grid usa-banner-inner">
      <img src="/assets/img/favicons/favicon-57.png" alt="U.S. flag">
      <p>An official website of the United States government</p>
      <button class="usa-accordion-button usa-banner-button"
        aria-expanded="false" aria-controls="gov-banner">
        <span class="usa-banner-button-text">Here's how you know</span>
      </button>
      </div>`

**Comment by kkoryaka** [comment]
In our new State template v5.5 we have added several navigation options. please see them here.
http://beta.template.webstandards.ca.gov/sample/navigation-full-width-icons.html
http://beta.template.webstandards.ca.gov/sample/navigation-full-width.html
http://beta.template.webstandards.ca.gov/sample/navigation-megamenu-flex.html

**Comment by lukefretwell** [comment]
@artuoma thank you!

**Comment by markaplet** [comment]
Sorry I know this is a little old, but I thought I would throw my ¢2 in. I think that the blue bar across the top is doing exactly that. It adds the CA logo to the utility bar. When we create alternate designs we tend to use that as a way of tying it back as an official CA Gov site.

**Comment by artuoma** [comment]
I agree Mark, I think the question at this point is how obvious do we make it and do we spell it out?

**Comment by rkojik** [comment]
@markaplet @artuoma  I agree, it certainly does satisfy the branding aspect. The part I'm interested in -- do users of CA services find the "here's how you know" content helpful? (re: official gov site, make sure you don't share sensitive info, and secure through https). 

My hypothesis is that it's one of two ways (or in between somewhere): 1. "Who cares" feature, just let me accomplish my task, or... 2. Thanks for trying to help me protect my info. The answer is probably both, but which one is more? We would need to research in order to find that out.
