### ISSUE TITLE
Add copy, paste and cut icons to the CAGov font library

### ISSUE THREAD

**Issue by kkoryaka** [Office-of-Digital-Innovation/California-State-Web-Template#376]
Add new copy, paste and cut icons to the CAGov font library
Example: 
![icons](https://user-images.githubusercontent.com/31669748/176060371-f33d9837-16e9-42cc-94c5-6d79f93a3707.jpg)

**Comment by kkoryaka** [comment]
@Courtney-Chittock I will ass screenshots and put them here

**Comment by kkoryaka** [comment]
@Courtney-Chittock here is screenshot. Please review:
![Screen Shot 2022-07-08 at 11 41 56 AM](https://user-images.githubusercontent.com/31669748/178051818-ecd285ca-43c9-409b-8f4c-23051676ead0.png)

**Comment by Courtney-Chittock** [comment]
@kkoryaka most Paste icons tend to illustrate something being added to the clipboard. Rough example:
![image](https://user-images.githubusercontent.com/99773875/179260119-da672986-4827-48e1-b26f-5b52487ae2af.png)
I would recommend adding that for context, but otherwise looks good!
(Side note: hilarious that floppy disks are still the go-to for Save icons :D)

**Comment by kkoryaka** [comment]
There you go
![Screen Shot 2022-07-26 at 11 50 44 AM](https://user-images.githubusercontent.com/31669748/181088058-2474c30c-84ec-4517-8be1-ab1c762ff631.png)
